### ISSUE TITLE
Zero division panic with datetime axis and short span of data

### ISSUE THREAD

**Issue by kangalioo** [plotters-rs/plotters#190]
Hi,

when rendering a plot with a datetime x axis where all data points lie on a single day, plotters crashes because of a divide-by-zero attempt:

```
thread 'serenity client' panicked at 'attempt to divide by zero', /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/coord/ranged1d/types/datetime.rs:205:24
stack backtrace:
[snipped]
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: <plotters::coord::ranged1d::types::datetime::RangedDate<D> as plotters::coord::ranged1d::Ranged>::key_points
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/coord/ranged1d/types/datetime.rs:205
  15: plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>::draw_mesh
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/coord/ranged2d/cartesian.rs:57
  16: plotters::drawing::area::DrawingArea<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh::{{closure}}
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/drawing/area.rs:199
  17: plotters::drawing::area::DrawingArea<DB,CT>::backend_ops
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/drawing/area.rs:277
  18: plotters::drawing::area::DrawingArea<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/drawing/area.rs:198
  19: plotters::chart::context::ChartContext<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh_lines
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/chart/context.rs:170
  20: plotters::chart::context::ChartContext<DB,plotters::coord::ranged2d::cartesian::Cartesian2d<X,Y>>::draw_mesh
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/chart/context.rs:481
  21: plotters::chart::mesh::MeshStyle<X,Y,DB>::draw
             at /home/kangalioo/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.0/src/chart/mesh.rs:440
[snipped]
```

**Comment by 38** [comment]
Hi there, I guess I know why this is happening and it would be nice if you can provide a reproduce so that I can confirm this is exact fix to this bug. Thanks!

**Comment by kangalioo** [comment]
Sorry for big delay

```rust
use plotters::prelude::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
	let root = BitMapBackend::new("0.png", (640, 480)).into_drawing_area();

	let now = chrono::offset::Local::now().date();
	let mut chart = ChartBuilder::on(&root).build_cartesian_2d(now..now, 0..10)?;

	chart.configure_mesh().draw()?;
	Ok(())
}
```

**Comment by estokes** [comment]
I am also hitting this bug, I think on line 205 there is some floating point error causing ceil() to return a 0 because the number is less than 1 by epsilon. I think you could just change line 205 to,

```
        let week_per_point = min(1, ((total_weeks as f64) / (max_points as f64)).ceil() as usize);
```

and that would likely fix it

**Comment by drager** [comment]
Yeah, I'm also hitting this. I have minute data for e.g. today:

To: 2021-08-02T08:00:00Z
From: 2021-08-02T09:14:00Z

**Comment by Stephin95** [comment]
The same issue here. When I input the date-time range with minute data I get this error
