### ISSUE TITLE
[BUG] Cannot access a Thread Local Storage value during or after destruction

### ISSUE THREAD

**Issue by fabianboesiger** [plotters-rs/plotters#306]
First of all, thanks for this beautiful library.

I'm attempting to draw a plot on `Drop`, in a pretty specific way. I use plotters version `0.3.1`.
Please take a look at the following example code:

```rust
use std::cell::RefCell;

use plotters::prelude::*;

fn main() {
    {
        thread_local! {
            static TEST: RefCell<Test> = RefCell::new(Test());
        }
        TEST.with(|_| {});
    }
    // With a single thread local static, everything works fine.
    {
        thread_local! {
            static TEST: RefCell<Test> = RefCell::new(Test());
        }
        TEST.with(|_| {});
    }
    
}

struct Test();

impl Drop for Test {
    // Draw a plot on drop.
    fn drop(&mut self) {
        let root = BitMapBackend::new("test.png", (100, 100))
                .into_drawing_area();

        let mut chart = ChartBuilder::on(&root)
            .caption("Test", 30)
            .build_cartesian_2d(0..0, 0..0)
            .unwrap();

        chart
            .configure_series_labels()
            .draw()
            .unwrap();
    }
}
```

The code above results in the following error

```
thread 'main' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::expect
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1241:23
   4: std::thread::local::LocalKey<T>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
   5: plotters::style::font::ttf::load_font_data
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/style/font/ttf.rs:122:32
   6: <plotters::style::font::ttf::FontDataInternal as plotters::style::font::FontData>::new
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/style/font/ttf.rs:202:29
   7: plotters::style::font::font_desc::FontDesc::new
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/style/font/font_desc.rs:36:19
   8: <plotters::style::font::font_desc::FontDesc as core::convert::From<(plotters_backend::text::FontFamily,T)>>::from
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/style/font/font_desc.rs:165:9
   9: <T as core::convert::Into<U>>::into
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/convert/mod.rs:540:9
  10: <plotters::style::text::TextStyle as core::convert::From<T>>::from
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/style/text.rs:202:19
  11: <u32 as plotters::style::text::IntoTextStyle>::into_text_style
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/style/text.rs:150:9
  12: plotters::chart::builder::ChartBuilder<DB>::caption
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.1/src/chart/builder.rs:153:13
  13: <multiple_plots::Test as core::ops::drop::Drop>::drop
             at ./examples/multiple-plots.rs:28:25
  14: core::ptr::drop_in_place<multiple_plots::Test>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  15: core::ptr::drop_in_place<core::cell::UnsafeCell<multiple_plots::Test>>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  16: core::ptr::drop_in_place<core::cell::RefCell<multiple_plots::Test>>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  17: core::ptr::drop_in_place<core::option::Option<core::cell::RefCell<multiple_plots::Test>>>
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  18: core::mem::drop
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/mem/mod.rs:896:24
  19: std::thread::local::fast::destroy_value
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:655:13
  20: __call_tls_dtors
  21: <unknown>
  22: exit
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

It seems to have something to do with loading fonts, so please tell me if this is the wrong place to report this issue.

**Comment by facorread** [comment]
`FONT_OBJECT_CACHE` is a `thread_local` global static object, I am wondering if refactoring as a member of `ChartContext` could help avoid this panic.

**Comment by facorread** [comment]
See the full backtrace below. If I read it correctly, frame 17 reveals that `thread_local` static objects are held internally in a HashMap. I am not sure Rust is in a position to make guarantees regarding the drop order of these objects. My suggestion would be to avoid using `plotters` while dropping variables.

```
thread 'main' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:418:26
stack backtrace:
   0:     0x7ff6b78dfe2f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6b78dfe2f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6b78dfe2f - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff6b78dfe2f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff6b78f045a - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff6b78dda39 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff6b78e24ab - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff6b78e24ab - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff6b78e24ab - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff6b78e209e - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff6b78e2aa1 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff6b78e295d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  12:     0x7ff6b78e0737 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff6b78e2639 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff6b78f6cd5 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  15:     0x7ff6b78f6d73 - core::result::unwrap_failed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\result.rs:1785
  16:     0x7ff6b77bdb88 - enum$<core::result::Result<enum$<core::option::Option<plotters::style::font::ttf::FontExt>, 0, 2, Some>,std::thread::local::AccessError>, 0, 3, Ok>::expect<enum$<core::option::Option<plotters::style::font::ttf::FontExt>, 0, 2, Some>,std::thread::local::Ac
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\result.rs:1035
  17:     0x7ff6b77cd5a3 - std::thread::local::LocalKey<core::cell::RefCell<std::collections::hash::map::HashMap<alloc::string::String,plotters::style::font::ttf::FontExt,std::collections::hash::map::RandomState> > >::with<core::cell::RefCell<std::collections::hash::map::HashMap<al
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:418
  18:     0x7ff6b77c4c61 - plotters::style::font::ttf::load_font_data
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\style\font\ttf.rs:122
  19:     0x7ff6b77c5ff7 - plotters::style::font::ttf::impl$5::new
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\style\font\ttf.rs:202
  20:     0x7ff6b77c079f - plotters::style::font::font_desc::FontDesc::new
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\style\font\font_desc.rs:36
  21:     0x7ff6b779d5c7 - plotters::style::font::font_desc::impl$3::from<u32>
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\style\font\font_desc.rs:165
  22:     0x7ff6b77aebf9 - core::convert::impl$3::into<tuple$<enum$<plotters_backend::text::FontFamily>,u32>,plotters::style::font::font_desc::FontDesc>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\convert\mod.rs:550
  23:     0x7ff6b77b5a58 - plotters::style::text::impl$14::from<tuple$<enum$<plotters_backend::text::FontFamily>,u32> >
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\style\text.rs:202
  24:     0x7ff6b77b59fa - plotters::style::text::impl$6::into_text_style<plotters::drawing::area::DrawingArea<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap::RGBPixel>,plotters::coord::Shift> >
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\style\text.rs:150
  25:     0x7ff6b77b90c3 - plotters::chart::builder::ChartBuilder<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap::RGBPixel> >::caption<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap::RGBPixel>,str,u32>
                               at C:\Users\nool.info\.cargo\registry\src\github.com-1ecc6299db9ec823\plotters-0.3.1\src\chart\builder.rs:153
  26:     0x7ff6b77bca79 - plotters_306::impl$0::drop
                               at D:\scratch\plotters-306\src\main.rs:30
  27:     0x7ff6b77bb68e - core::ptr::drop_in_place<plotters_306::Test>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ptr\mod.rs:448
  28:     0x7ff6b77bb9fe - core::ptr::drop_in_place<core::cell::UnsafeCell<plotters_306::Test> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ptr\mod.rs:448
  29:     0x7ff6b77bb972 - core::ptr::drop_in_place<core::cell::RefCell<plotters_306::Test> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ptr\mod.rs:448
  30:     0x7ff6b77bbe77 - core::ptr::drop_in_place<enum$<core::option::Option<core::cell::RefCell<plotters_306::Test> > > >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ptr\mod.rs:448
  31:     0x7ff6b7798f28 - core::mem::drop<enum$<core::option::Option<core::cell::RefCell<plotters_306::Test> > > >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\mem\mod.rs:968
  32:     0x7ff6b77ba067 - std::thread::local::fast::destroy_value<core::cell::RefCell<plotters_306::Test> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:1030
  33:     0x7ff6b78e5099 - std::sys::windows::thread_local_dtor::run_keyless_dtors
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys\windows\thread_local_dtor.rs:24
  34:     0x7ff6b78e5099 - std::sys::windows::thread_local_key::on_tls_callback
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys\windows\thread_local_key.rs:200
  35:     0x7ffefc4443fa - RtlInitializeConditionVariable
  36:     0x7ffefc400277 - RtlActivateActivationContextUnsafeFast
  37:     0x7ffefc402f91 - LdrLoadAlternateResourceModuleEx
  38:     0x7ffefc4148b1 - LdrShutdownProcess
  39:     0x7ffefc41465d - RtlExitUserProcess
  40:     0x7ffefb92c66b - ExitProcess
  41:     0x7ffef99e9fec - exit
  42:     0x7ffef99ea0c1 - exit
  43:     0x7ff6b78f51db - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:295
  44:     0x7ffefb9254e0 - BaseThreadInitThunk
  45:     0x7ffefc3c485b - RtlUserThreadStart
thread 'main' panicked at 'panic in a function that cannot unwind', library\core\src\panicking.rs:107:58
stack backtrace:
   0:     0x7ff6b78dfe2f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6b78dfe2f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6b78dfe2f - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff6b78dfe2f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff6b78f045a - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff6b78dda39 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff6b78e24ab - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff6b78e24ab - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff6b78e24ab - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff6b78e209e - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff6b78e2aa1 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff6b78e2922 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:586
  12:     0x7ff6b78e0737 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff6b78e2639 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff6b78f6c75 - core::panicking::panic_no_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:110
  15:     0x7ff6b77ba096 - std::thread::local::fast::destroy_value<core::cell::RefCell<plotters_306::Test> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:1014
  16:     0x7ffef03e1030 - <unknown>
  17:     0x7ffef03e4828 - is_exception_typeof
  18:     0x7ffefc4686b6 - RtlCaptureContext2
  19:     0x7ff6b77ba067 - std::thread::local::fast::destroy_value<core::cell::RefCell<plotters_306::Test> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:1030
  20:     0x7ff6b78e5099 - std::sys::windows::thread_local_dtor::run_keyless_dtors
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys\windows\thread_local_dtor.rs:24
  21:     0x7ff6b78e5099 - std::sys::windows::thread_local_key::on_tls_callback
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys\windows\thread_local_key.rs:200
  22:     0x7ffefc4443fa - RtlInitializeConditionVariable
  23:     0x7ffefc400277 - RtlActivateActivationContextUnsafeFast
  24:     0x7ffefc402f91 - LdrLoadAlternateResourceModuleEx
  25:     0x7ffefc4148b1 - LdrShutdownProcess
  26:     0x7ffefc41465d - RtlExitUserProcess
  27:     0x7ffefb92c66b - ExitProcess
  28:     0x7ffef99e9fec - exit
  29:     0x7ffef99ea0c1 - exit
  30:     0x7ff6b78f51db - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:295
  31:     0x7ffefb9254e0 - BaseThreadInitThunk
  32:     0x7ffefc3c485b - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\plotters-306.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
n
```
